// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SubjectSelection.Models;
using System;

namespace SubjectSelection.Migrations
{
    [DbContext(typeof(SubjectSelectionDbContext))]
    partial class SubjectSelectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubjectSelection.Models.ExclusiveSubjectLists", b =>
                {
                    b.Property<int>("ExclusiveSubjectListsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SubjectListAId");

                    b.Property<int>("SubjectListBId");

                    b.HasKey("ExclusiveSubjectListsId");

                    b.HasIndex("SubjectListAId");

                    b.HasIndex("SubjectListBId");

                    b.ToTable("ExclusiveSubjectLists");
                });

            modelBuilder.Entity("SubjectSelection.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<string>("ClassDate");

                    b.Property<string>("Name");

                    b.Property<int>("SubjectId");

                    b.HasKey("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SubjectSelection.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("ParentListId");

                    b.HasKey("SubjectId");

                    b.HasIndex("ParentListId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SubjectSelection.Models.SubjectList", b =>
                {
                    b.Property<int>("SubjectListId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OwnerId");

                    b.HasKey("SubjectListId");

                    b.HasIndex("OwnerId");

                    b.ToTable("SubjectLists");
                });

            modelBuilder.Entity("SubjectSelection.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("StudentCardId");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SubjectSelection.Models.UserEditableLists", b =>
                {
                    b.Property<int>("UserEditableListsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SubjectListId");

                    b.Property<int>("UserId");

                    b.HasKey("UserEditableListsId");

                    b.HasIndex("SubjectListId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEditableLists");
                });

            modelBuilder.Entity("SubjectSelection.Models.UserEditableSubjects", b =>
                {
                    b.Property<int>("UserEditableSubjectsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SubjectId");

                    b.Property<int>("UserId");

                    b.HasKey("UserEditableSubjectsId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEditableSubjects");
                });

            modelBuilder.Entity("SubjectSelection.Models.UserGroups", b =>
                {
                    b.Property<int>("UserGroupsId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<int>("UserId");

                    b.HasKey("UserGroupsId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("SubjectSelection.Models.ExclusiveSubjectLists", b =>
                {
                    b.HasOne("SubjectSelection.Models.SubjectList", "SubjectListA")
                        .WithMany("ExclusiveSubjectListsA")
                        .HasForeignKey("SubjectListAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubjectSelection.Models.SubjectList", "SubjectListB")
                        .WithMany("ExclusiveSubjectListsB")
                        .HasForeignKey("SubjectListBId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubjectSelection.Models.Group", b =>
                {
                    b.HasOne("SubjectSelection.Models.Subject", "Subject")
                        .WithMany("Groups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SubjectSelection.Models.Subject", b =>
                {
                    b.HasOne("SubjectSelection.Models.SubjectList", "ParentList")
                        .WithMany("Subjects")
                        .HasForeignKey("ParentListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SubjectSelection.Models.SubjectList", b =>
                {
                    b.HasOne("SubjectSelection.Models.User", "Owner")
                        .WithMany("UserOwnedSubjectLists")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SubjectSelection.Models.UserEditableLists", b =>
                {
                    b.HasOne("SubjectSelection.Models.SubjectList", "SubjectList")
                        .WithMany("UsersWhoCanEdit")
                        .HasForeignKey("SubjectListId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubjectSelection.Models.User", "User")
                        .WithMany("ListsEditableByUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubjectSelection.Models.UserEditableSubjects", b =>
                {
                    b.HasOne("SubjectSelection.Models.Subject", "Subject")
                        .WithMany("UsersWhoCanEdit")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubjectSelection.Models.User", "User")
                        .WithMany("SubjectsEditableByUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubjectSelection.Models.UserGroups", b =>
                {
                    b.HasOne("SubjectSelection.Models.Group", "Group")
                        .WithMany("UsersInGroup")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubjectSelection.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
